version: "3"

services:
  hub:
    image: selenium/hub:3.14
    ports: 
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
      image: davidsso52/selenium-docker
      depends_on:
        - chrome
        - firefox
      environment:
        - HUB_HOST=hub
        - MODULE=search-module.xml
      volumes:
        - ./search-result:/usr/share/udemy/test-output
  search-module2:
    image: davidsso52/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result2:/usr/share/udemy/test-output
